global with sharing class WTB_Constants {
	global static String WTBAPIUSERID = 'wtbapiuser';
	global static String WTBAPIUSERVALUE = 'verified';
	global static String ACCESS_DENIED_MESSAGE = 'Access denied. Not a wtb user.';
	global static String STATUS_OK = 'OK';
	global static String DEFAULT_LOCALE = 'EN-US';
	global static String GOOGLE_GEOCODE_URL = 'http://maps.google.com/maps/api/geocode/json?sensor=false&address=';
	global static Integer NUM_RESULTS = 15;
	global static Double RADIUS = 50;
	global static String CLIENT_ID = '';
	global static String SIGNATURE = '';
}